FROM node:20.18.0

# Set the working directory in the container
WORKDIR '/app'

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

CMD ["npm", "run", "start"]